#ifndef PFC_PARAMETER_H
#define PFC_PARAMETER_H

#include "DCLF32.h"

#define AC_FREQUENCY 50.0f
#define MCU_FREQUENCY 170000000.0f
#define HRPWM_PRESCALE 16
#define HRPWM_PERIOD_Uint 4000
#define PWM_FREQUENCY (MCU_FREQUENCY*HRPWM_PRESCALE)/(HRPWM_PERIOD_Uint)
#define ISR_FREQUENCY PWM_FREQUENCY

#define PFC_GI_RUN DCL_runDF22_C1
#define PFC_GV_RUN DCL_runPI_C2
#define PFC_NOTCH_RUN DCL_runDF22_C4

#endif
